[project]
name = "harmonyos-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.1.2",
    "mcp[cli]>=1.6.0",
]
